name: GitHub Actions Build and Deploy Demo

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
  
jobs:
  build-and-deploy:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
    - name: Install Dependencies
      env:
        THEOS: theos
      run: |
        brew install ldid fakeroot
        git clone --depth=1 --recursive https://github.com/theos/theos.git $THEOS
        git submodule update --init --recursive

    - name: Build Package
      env:
        THEOS: theos
      run: make package

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
