name: iOS pod CI

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Deploy to CocoapodsPre
      run: |
        set -eo pipefail
        
        VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo $VERSION
        export LIB_VERSION=$VERSION
        
        sed -i "" "s/NSString *const TIoTLinkKitShortVersionString.*/NSString *const TIoTLinkKitShortVersionString = @"$VERSION";/g" Source/LinkSDK/QCFoundation/TIoTCoreAppEnvironment.m
        
        pod lib lint --verbose --allow-warnings --use-libraries
        pod trunk push --verbose --allow-warnings --use-libraries
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.IOT_COCOAPODS_TRUNK_TOKEN }}
