name: iOS CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]
      
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GPG
      run: brew install gnupg
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Decrypt large secret
      run: sh .github/script/import_provisioning.sh Debug
      env:
        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
        P12_EXPORT_CCHARLESREN_PASSWORD: ${{ secrets.IOT_P12_EXPORT_PASSWORD }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: |
        sh .github/script/archive.sh Debug
    - name: Deploy App to PGY
#      run: curl -F 'file=@./LinkApp.ipa' -F "_api_key=$RELEASE_PGYER_API_KEY" https://www.pgyer.com/apiv2/app/upload
      run: curl -F "file=@./LinkApp.ipa" -F "_api_key=$RELEASE_PGYER_API_KEY" https://upload.pgyer.com/apiv2/app/upload
      env:
        RELEASE_PGYER_API_KEY: ${{ secrets.IOT_PGYER_API_KEY }}
    - name: upload dSYM
      run: ./Pods/Fabric/upload-symbols -gsp ./LinkApp/Supporting\ Files/GoogleService-Info.plist -p ios ./LinkApp.xcarchive/dSYMs/腾讯连连.app.dSYM
