name: iOS CI

on: [push, pull_request]
      
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: pod cache
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Install GPG
      run: brew install gnupg
    - name: install fir
      run: gem install fir-cli
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Decrypt large secret
      run: sh .github/script/import_provisioning.sh Debug
      env:
        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
        P12_EXPORT_CCHARLESREN_PASSWORD: ${{ secrets.IOT_P12_EXPORT_PASSWORD }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.5.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        export GIT_BRANCH_IMAGE_VERSION=$VERSION
        
        sh .github/script/archive.sh Debug
        sh .github/script/sdkDemoArchive.sh Debug
        
        ls -l
        
    - name: Deploy App to fir
      run: |
        rc=$(git rev-parse --short HEAD)
        rl=$(git log --pretty=format:"%s" $rc -1)
        
        fir publish LinkApp.ipa -T $RELEASE_PGYER_API_KEY -c "$rl" --oversea_turbo --force_pin_history -V
        fir publish LinkSDKDemo.ipa -T $RELEASE_PGYER_API_KEY --oversea_turbo --force_pin_history -V
      env:
        RELEASE_PGYER_API_KEY: ${{ secrets.IOT_FIRIM_API_TOKEN }}
        
    - name: upload dSYM
      run: |
        ./Pods/Fabric/upload-symbols -gsp ./Source/LinkApp/Supporting\ Files/GoogleService-Info.plist -p ios ./LinkApp.xcarchive/dSYMs/LinkApp.app.dSYM
        ./Pods/Fabric/upload-symbols -gsp ./Source/LinkSDKDemo/GoogleService-Info.plist -p ios ./LinkSDKDemo.xcarchive/dSYMs/LinkSDKDemo.app.dSYM
